# config/packages/security.yaml
security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users
                property: userName
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        api:
            pattern: ^/api
            stateless: true
            http_basic: ~  # Utiliser HTTP Basic au lieu de JWT
        
        main:
            lazy: true
            provider: app_user_provider
    
    # Access control configuration
    access_control:
    - { path: ^/api/login, roles: PUBLIC_ACCESS }
    - { path: ^/api/register, roles: PUBLIC_ACCESS }
    - { path: ^/api/v1/(video|editor|category)/game$, methods: [GET], roles: PUBLIC_ACCESS }
    - { path: ^/api/v1/(video|editor|category)/\d+$, methods: [GET], roles: PUBLIC_ACCESS }
    - { path: ^/api, roles: PUBLIC_ACCESS }