# config/routes.yaml
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api:
    resource: .
    type: api_platform
    prefix: /api

app.swagger_ui:
    path: /api/docs
    methods: GET
    defaults: { _controller: api_platform.swagger.action.ui }